name: "Get & Cache Dependencies"
description: "Get the dependencies (via npm) and cache them"
runs:
  # this define the type we are trying to use vvvv in this situation we need to define "Composite"
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
